/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>
#include "stm32f446xx.h"

#define TIM2EN 0
#define ARPE 7
#define UIE 0
#define UIF 0
#define PA5 5
#define CEN 0
#define UG 0

void TIM2_IRQHandler()
{
	if(TIM2->SR & (1<<UIF))
	{
		TIM2->SR = ~(1<<UIF);
		GPIOA->ODR ^= (1<<PA5);
	}
}

void timer2_init(void)
{
	RCC->APB1ENR |= (1<<TIM2EN);
	TIM2->PSC = 15;
	TIM2->ARR = 999999;
	TIM2->EGR |= (1<<UG);
	TIM2->CR1 |= (1<<ARPE);
	TIM2->DIER |= (1<<UIE);
	NVIC->ISER[0] |= (1<<28);
	NVIC->IPR[28] = (1<<4);
}

void toggle_1s()
{
	TIM2->CR1 |= (1<<CEN);
}

void led_en()
{
	GPIOA_CLK_EN();
	GPIOA->MODER &= ~(0x3<<(PA5*2));
	GPIOA->MODER |= (1<<(PA5*2));
	GPIOA->OTYPER &= ~(1<<PA5);
}

int main(void)
{
	led_en();
	timer2_init();
	toggle_1s();
	for(;;);
}
