/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>

#include "TIM.h"
#include "ADC.h"
#include "DMA.h"
#include "USART.h"
#include "stm32f446xx.h"

#define SAMPLES 100
volatile uint8_t c = 0;

uint16_t adc_buffer[SAMPLES];
char tx_buffer[1000];

void DMA2_Stream0_IRQHandler(void)
{
    if(DMA2->LISR & (1 << 5))
    {
    	c = 1;
        DMA2->LIFCR |= (1 << 5);

        DMA1->S[6].CR &= ~(1 << 0);
        while(DMA1->S[6].CR & (1 << 0));
        DMA1->HIFCR |= (0x3D << 16);
        // 100 samples * 2 bytes each = 200
        DMA1->S[6].NDTR = SAMPLES * 10;
        DMA1->S[6].CR |= (1 << 0);
    }
}

void GPIO_init(void)
{
	GPIOA_PCLK_EN();
	// 2. Set PA2 to Alternate Function Mode (10)
	GPIOA->MODER &= ~(0x3 << (2 * 2));
	GPIOA->MODER |= (0x2 << (2 * 2));

	// 3. Map PA2 to AF7 (USART2) in AFR[0] (Low Register)
	// Each pin takes 4 bits, so PA2 starts at bit 8
	GPIOA->AFR[0] &= ~(0xF << (2 * 4));
	GPIOA->AFR[0] |= (0x7 << (2 * 4));
}

int main(void)
{
	GPIO_init();
	USART_init();
	DMA1_init(tx_buffer);
	DMA2_init(adc_buffer);
	ADC_init();
	ADC_Read();
	TIM_init();
	TIM_start();
	USART_start();
	for(;;)
	{
		if(c == 1 )
		{
			int idx = 0;
			for (int i = 0; i < SAMPLES; i++)
		        idx += sprintf(&tx_buffer[idx], "%d.%u C\r\n", i,adc_buffer[i]);

			c = 0;
		}
	}
}



