/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>
#include "stm32f446xx.h"
#include "stm32f446xx_ADC_driver.h"
#include "stm32f446xx_TIM_driver.h"

#define PA0 0

void ADC_Inits(ADC_Handle_t *ADC_Handle)
{
	ADC_Handle->pADCx = ADC1;
	ADC_Handle->ADC_Config.Seq_Len = 0;
	ADC_Handle->ADC_Config.Seq_Channel12_7 = 0;
	ADC_Handle->ADC_Config.Seq_Channel16_13 = 0;
	ADC_Handle->ADC_Config.Seq_Channel6_1 = 0;
	ADC_Handle->ADC_Config.smpr1 = 0;
	ADC_Handle->ADC_Config.smpr2 = (0x7 << 0);
	ADC_Init(ADC_Handle);
}

void TIM_Inits(TIM_Handle_t *TIM_Handle)
{
	TIM_Handle->pTIMx = TIM3;
	TIM_Handle->TIM_Config.Prescalar = 159;
	TIM_Handle->TIM_Config.Period = 999;
	TIM_Trigger_config(TIM3,TIM_TRIGGER_ON_UPDATE);
}

int main(void)
{
	ADC_Handle_t ADC_1;
	TIM_Handle_t TIM_3;
	// GPIOA PERIPHERAL CLOCK
	GPIOA_PCLK_EN();
	// Analog mode
	GPIOA->MODER |= (0X3<<(PA0*2));
	//ADC_Inits(&ADC_1);
		ADC_1.pADCx = ADC1;
		ADC_1.ADC_Config.Seq_Len = 0;
		ADC_1.ADC_Config.Seq_Channel12_7 = 0;
		ADC_1.ADC_Config.Seq_Channel16_13 = 0;
		ADC_1.ADC_Config.Seq_Channel6_1 = 0;
		ADC_1.ADC_Config.smpr1 = 0;
		ADC_1.ADC_Config.smpr2 = (0x7 << 0);
		ADC_Init(&ADC_1);
	//TIM_Inits(&TIM_3);
		TIM_3.pTIMx = TIM3;
		TIM_3.TIM_Config.Prescalar = 159;
		TIM_3.TIM_Config.Period = 999;
		TIM_Trigger_config(TIM3,TIM_TRIGGER_ON_UPDATE);
	TIM_Counter_Start(TIM_3.pTIMx);
	ADC_External_Trigger(ADC_1.pADCx);
	for(;;)
	{
		uint16_t dr = ADC1->DR;
		float temp = ((dr*3.3) / 4095.0)*100.0;
		printf("T : %.3f%cC\n",temp,'°');
	}
}
