/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>

#include "TIM.h"
#include "ADC.h"
#include "DMA.h"
#include "USART.h"
#include "stm32f446xx.h"

#define SAMPLES 100

// double buffer
uint16_t adc_buffer[SAMPLES*2];

void DMA2_Stream0_IRQHandler(void)
{
	// transfer complete interrupt flag set or not
	if(DMA2->LISR & (1<<5))
	{
		// clear transfer complete flag
		DMA2->LIFCR |= (1<<5);
		// if current target is set DMA is writing to buffer 1
		if(DMA2->S[0].CR & (1<<19))
			// change the DMA memread location to start of the buffer
			DMA1->S[6].M0AR = (uint32_t)adc_buffer;
		// if 0 dma is writing in buffer 0
		else if(!(DMA2->S[0].CR & (1<<19)))
			// change dma read location to 2nd buffer location
			DMA1->S[6].M0AR = (uint32_t)&adc_buffer[SAMPLES];

		// disable dma1
		DMA1->S[6].CR &= ~(1 << 0);
		while(DMA1->S[6].CR & (1 << 0));

		// clearing dma 1 interrupt flags
		DMA1->HIFCR |= (0x3D << 16);

		// no of data to be transferred set to 200 bytes
		DMA1->S[6].NDTR = SAMPLES*2;
		// restart dma1
		DMA1->S[6].CR |= (1 << 0);
	}
}

void GPIO_init(void)
{
	GPIOA_PCLK_EN();
	// 2. Set PA2 to Alternate Function Mode (10)
	GPIOA->MODER &= ~(0x3 << (2 * 2));
	GPIOA->MODER |= (0x2 << (2 * 2));

	GPIOA->OSPEEDR |= (0x3 << (2 * 2)); // High speed PA2


	// 3. Map PA2 to AF7 (USART2) in AFR[0] (Low Register)
	// Each pin takes 4 bits, so PA2 starts at bit 8
	GPIOA->AFR[0] &= ~(0xF << (2 * 4));
	GPIOA->AFR[0] |= (0x7 << (2 * 4));
	// PA0 in anlog mode
	GPIOA->MODER |= (0X3 << (0*2));
}

int main(void)
{
	// intializing peripherals
	GPIO_init();
	USART_init();
	DMA2_init(adc_buffer);
	DMA1_init();
	ADC_init();
	ADC_Read();
	TIM_init();
	TIM_start();
	USART_start();
	// loop
	for(;;);
}



