/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>
#include "stm32f446xx.h"

#define PC13 13
#define PA5 5

void EXTI15_10_IRQHandler(void)
{
	if(EXTI->PR&(1<<PC13))
	{
		// clear interrupt
		EXTI->PR |= (1<<PC13);
		// TOGGLE OUPUT
		GPIOA->ODR ^= (1<<PA5);
	}
}


void set_input(void)
{
	GPIOC_CLK_EN();
	// input mode
	GPIOC->MODER &= ~(0X3 << (PC13*2));
	// no pullup or pull down
	GPIOC->PUPDR &= ~(0X3 << (PC13*2));
}

void set_output(void)
{
	GPIOA_CLK_EN();
	//output led
	GPIOA->MODER &= ~(0X3 << (PA5*2));
	GPIOA->MODER |= (0X1 << (PA5*2));
}

void set_interrupt(void)
{
	// enable syscfg clk
	RCC->APB2ENR |= (1<<14);
	// PC13 EXTERNAL INTERRUPT
	SYSCFG->EXTICR[3] &= ~(0xF<<4);
	SYSCFG->EXTICR[3] |= (0X2 << 4);
	// unmasking ONLY 13th interrupt line
	EXTI->IMR |= (1<<13);
	// ONLY 13TH LINE FOR Rising edge interrupt not falling edge
	EXTI->RTSR |= (1<<13);
	EXTI->FTSR &= ~(1<<13);

	NVIC->ISER[1] = (1<<(40-32));
	NVIC->IPR[40] = (1<<4);
}


int main(void)
{
	set_input();
	set_output();
	set_interrupt();
	for(;;);
}
