/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>
#include "stm32f446xx.h"
#include "stm32f446xx_adc_driver.h"

// SET PA0 AS ANALOG
#define PA0 0
// RCC bits
#define ADC1EN 8

ADC_Handle_t ADC1_Handle;


int main(void)
{
	// GPIOA PERIPHERAL CLOCK
	GPIOA_PCLK_EN();
	// Analog mode
	GPIOA->MODER |= (0X3<<(PA0*2));
	// ADC clock
	RCC->APB2ENR |= (1<<ADC1EN);
	ADC1_Handle.pADCx = ADC1;
	ADC1_Handle.ADC_Config.Seq_Len = 0;
	ADC1_Handle.ADC_Config.Seq_Channel16_13 = 0;
	ADC1_Handle.ADC_Config.Seq_Channel12_7 = 0;
	ADC1_Handle.ADC_Config.Seq_Channel6_1 = 0;
	ADC1_Handle.ADC_Config.smpr1 = 0;
	ADC1_Handle.ADC_Config.smpr2 = (0x7<<0);
	ADC_Init(&ADC1_Handle);

	for(;;)
	{
		uint16_t dr = ADC_Read(ADC1);
		// temperature conversion
		float temp = ((dr*3.3) / 4095.0)*100.0;
		printf("T : %.3f%cC\n",temp,'°');
		// delay
		for(int i=0;i<1000000;i++);
	}
}









