/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include "i2c.h"
#include "BMP280.h"


int main(void)
{
    i2c_init();
    temp_init();
    pres_init();
	for(;;)
	{
		printf("T : %.3f %cC\n",get_temp(),'\u00B0');
		printf("P : %.3f hPa\n\n",get_pres()/100.0);
		for(int i=0;i<1000000;i++);
	}
}
